### PR TITLE
ScopedPointer -> unique_ptr part3

### PR DESCRIPTION
**Pull request by ghost**
Addresses #11

### CODE REVIEW

**Comment by ghost** [comment]
This is the last part of the series and 
well this works but I'm not sure if it's the way to go.
Please have a look and call it nonsense if it is.

**Comment by baconpaul** [comment]
its just the private->public swap that gives you pause?

I'm a `#define private public` kinda coder so I'm fine with that but want to make sure that's your only concern.

**Comment by ghost** [comment]
yes that's exactly where I was not sure if it's something you maybe don't want.

**Comment by baconpaul** [comment]
Nah that's how I would have done it!

**Pull request merged**
