### PR TITLE
Repository layout

### LINKED ISSUE #30: Further repository organization
All folders lowercase (to match Surge XT repo).

`Source` -> `src`
`Manual` -> `doc`
`Files`, `Fonts`, `Icon`, `Images`, `iPad`, `Spec` -> all move into `resources` (better name for `Spec` folder?)
Inside `Files` we have factory presets, move that to `resources/patches`
Inside `Files` we have factory themes, move that to `resources/themes`

Any .xcf (Sketch) files should be in `resources/assets`

### PR DESCRIPTION
**Pull request by ghost**
Monique has moved away from large commits across the repo,
the later this is done the more history will be blurred.
So here is my layout suggestion.
git blame and the like still works, but githubs History feature as well as some
"one-click-timeline-solutions" of some IDEs will be broken (showing this as the first commit).

The problem I have with this is: If I commit this, GH will display me as the one and only author
of all the files, which is far from the truth. Does anyone know a trick to prevent that from happening?
Otherwise I'd happily close this and ask @TommmyArn to do the commit (feel free to copy/paste of course).

Closes #30

### CODE REVIEW

**Comment by baconpaul** [comment]
Git log with follow still works if you git move unchanged files right? We grappled with same with surge and concluded it was inevitable that unfollowed history would be wrong

**Comment by baconpaul** [comment]
Sorry so in other words: yes the GitHub ui is broken but the history isn’t so I would be ok merging this if you are

**Comment by ghost** [comment]
yes git log --follow works, it's what i meant with "git blame and the like".
I am ok with whatever is the appropriate solution.

**Comment by baconpaul** [comment]
Yeah so the other option is close this pr modify the commit to change the author and push to main directly - I’m not sure I like that either though - thoughts?

**Comment by baconpaul** [comment]
Modify it so it tommy ci authored by you for instance? Or other way?

**Comment by ghost** [comment]
lets see, i tagged tommy too, easyest if he just copy/paste/pushes it. (if he wants)

**Comment by ghost** [comment]
Ok I changed the commiter to SST (I can't commit as a fake tommy in disguise, that would also be weird :) )
So I'm closing this one.

**Pull request closed without merging**
