### PR TITLE
ScopedPointer -> unique_ptr part1

### PR DESCRIPTION
**Pull request by ghost**
Addresses #11

### CODE REVIEW

**Comment by ghost** [comment]
I gave this a try in 3 parts

Part1 is all the pointers that could be replaced without conflict.
I hope it is not too big for a single pull request.

I ignored `mono_AudioDeviceManager` and `monique_ui_MIDIIO`,
`IS_STANDALONE_WITH_OWN_AUDIO_MANAGER_AND_MIDI_HANDLING` doesn't apply for me 
so I can't test compile any changes on these.

**Comment by baconpaul** [comment]
Tank you!

two thoughts

1. std::unique_ptr<XmlElement> xml = XmlDocument(settings_session_file).getDocumentElement();

i wonder if thst would be cleaner as auto xml = etc. increasingly we are moving to the auto everywhere idioms in the codebase here

2. you changed addandmakevisible(foo) to (foo.get()) which is ok but juce 6 seems more idiomatically to use the const & version so addandmakevisible(*foo)


Sorry for poor formatting here. On my phone. Let me know what you think about these two ideas?

**Comment by ghost** [comment]
Oh yes you mentioned the first point in the issue already, sorry about that.
But sure I can change all that. It will be tomorrow though.

**Comment by baconpaul** [comment]
No need to apologize! pleasure to have another dev on board

I can look and merge tomorrow no problem 

thanks!!

**Comment by ghost** [comment]
updated with your suggestions

**Comment by baconpaul** [comment]
Amazing thank you'

**Pull request merged**
