### PR TITLE
Warnings continued

### PR DESCRIPTION
**Pull request by ghost**
msvc:
- c4804/4805 unsafe use of bool/bool and float
- c4715/4099 confirmed to be gone
- /permissive-: change and/or/not words to operators
  (up for debate, compilers like it, human readers less so)

clang:
- int division in float context
- Wreorder-ctor (why not)

Addresses #16

### CODE REVIEW

**Comment by baconpaul** [comment]
I’m happy with and to && 

not in your diff but just above it there is a define constexpr as const - so we need that now we are 17 everywhere?

but looks good to me in a skim - feel feee to merge!

**Comment by baconpaul** [comment]
I’m happy with and to && 

not in your diff but just above it there is a define constexpr as const - so we need that now we are 17 everywhere?

but looks good to me in a skim - feel feee to merge!

**Comment by ghost** [comment]
probably not but I'm not on a windows machine right now, 
but since the checks don't run I can add that and force push maybe that wakes them up?

**Comment by baconpaul** [comment]
As you saw yeah subsequent pushes (force or additive) will re run ci

**Pull request merged**
