### PR TITLE
Add clang format

### PR DESCRIPTION
**Pull request by TommmyArn**

### CODE REVIEW

**Comment by TommmyArn** [comment]
To my eyes, this looks very readable. Please let me know what you think, or just add your suggestions / changes. We spend so much time on reading code, so it should be optimized for readability and of course beauty too! :-)

Another style thing. I'm a great fan of snake_case all, actually the C++ and STL standard and as I know the most readable one. What do you think?

**Comment by baconpaul** [comment]
Those look like fine choices to me. I generally like 4 space tabs indeed and start at LLVM.

For me, CLion will also just apply it automatically whenever i edit. Shall we do a one-time single commit to apply this format to every file in the source directory?

Also, in surge we fail the pipeline if you do a commit which isn't clang-formatted. Would you like to do the same with Monique? (That of course depends on the answer to the first question :) )

**Review by baconpaul — APPROVED** [review]

**Comment by baconpaul** [comment]
oh and happy to use `snake_case` following STL. As long as we decide, and don't use tabs or dos line endings, I'm happy :)

**Comment by TommmyArn** [comment]
> For me, CLion will also just apply it automatically whenever i edit. Shall we do a one-time single commit to apply this format to every file in the source directory?

Yes, had the same in mind.

**Comment by TommmyArn** [comment]
> Also, in surge we fail the pipeline if you do a commit which isn't clang-formatted. Would you like to do the same with Monique? (That of course depends on the answer to the first question :) )

Jepp!

**Comment by TommmyArn** [comment]
> oh and happy to use `snake_case` following STL. As long as we decide, and don't use tabs or dos line endings, I'm happy :)

Ok. Lets snake around. :D

**Comment by baconpaul** [comment]
OK!
So I think a good strategy is

1: you go ahead and commit this
2: in a *separate* commit run `clang-format -i` over all the code in Source and commit that. (It's useful to have one big 'reformat no other changes' commit in git history) and then
3: I'll get the clang-format pipeline rule up and running before the weekend by copying it from surge.

Sound good?

**Comment by TommmyArn** [comment]
Sounds good!

**Pull request merged**
